
object SearchQueries {

  val Filtered = Set(
    "adele",
    "anonymous",
    "candy crush",
    "christmas",
    "exo",
    "halloween",
    "jon stewart",
    "likes",
    "star wars"
  )

  val All = Set(
    "#aldubthevisitor",
    "#aldubnewcharacter",
    "greg hardy",
    "#manonthemoon",
    "ben carson",
    "#aldub16thweeksary",
    "#aldubthering",
    "#aldubperformstogether",
    "stone roses",
    "#nationalstressawarenessday",
    "seth rollins",
    "#jebcanfixit",
    "#justinhateshisfansparty",
    "jon stewart",
    "#aldubpreparepamore",
    "#respectlouis",
    "star trek",
    "5th of november",
    "candy crush",
    "coldplay",
    "#nationalsandwichday",
    "dj creme",
    "#youweresohotuntil",
    "#millionmaskmarch",
    "#thingstoleakinsteadofthealbum",
    "arsenal",
    "john terry",
    "#nationaldoughnutday",
    "west point",
    "benzema",
    "#1dhistory",
    "#twitterheart",
    "#electionday",
    "#redcups",
    "#marchforindia",
    "#opkkk",
    "#wegotyourbackmeng",
    "#cmaawards",
    "#stressin5words",
    "#bonfirenight",
    "#thewalkingdead",
    "#my3wordhappiness",
    "#mondaymotivation",
    "vernon davis",
    "#keystonexl",
    "#illshowyou",
    "andrew luck",
    "#happybirthdaykingkhan",
    "rachel dolezal",
    "chiraq",
    "patrick kane",
    "charlie hebdo",
    "his dark materials",
    "#youhadmeat",
    "di maria",
    "dusty baker",
    "google calendar",
    "fred thompson",
    "morgan",
    "#websummit",
    "ellie goulding",
    "dapper laughs",
    "justin bieber",
    "faisal mohammad",
    "jeb can fix it",
    "derrick rose",
    "warcraft",
    "spike lee",
    "#pbbthebigweekend",
    "h&amp",
    "eddie redmayne",
    "#empire",
    "sam burgess",
    "#illegalizeit",
    "christmas",
    "#fridayfeeling",
    "trump",
    "#e3now",
    "arundhati roy",
    "uc merced",
    "#9daysuntilmitam",
    "#blackops3",
    "#7daysuntilmitam",
    "#waiguru",
    "guy fawkes",
    "likes",
    "#thankyoubob",
    "bayern",
    "#xfactor",
    "#theapprentice",
    "black ops 3",
    "#scandal",
    "julius randle",
    "anonymous",
    "#demforum",
    "#oscarpistorius",
    "50 cent",
    "#sexontrial",
    "ken whisenhunt",
    "harry giles",
    "tristram hunt",
    "#exitpoll",
    "joseph randle",
    "mufc",
    "porzingis",
    "royals",
    "#pm23",
    "maine mendoza",
    "little mix",
    "chelsea",
    "sharm",
    "#8daysuntilmitam",
    "#melbournecup",
    "#royals",
    "#bencarsonwikipedia",
    "drake",
    "jonny gomes",
    "#kailashvijayvargiyaleaveindia",
    "#screamqueens",
    "#pmqs",
    "lingard",
    "donald trump",
    "#headachesin5words",
    "harvey",
    "adele",
    "#beingmaryjane",
    "mets",
    "mourinho",
    "#manilaneedsslflday2",
    "#indiaistolerant",
    "steve smith",
    "#htgawm",
    "#moboawards",
    "jacoby jones",
    "kamal haasan",
    "#seavsdal",
    "halloween",
    "balmain",
    "paul george",
    "lfc",
    "#cricketallstars",
    "#blizzcon",
    "seth curry",
    "#celebrityrestaurants",
    "rick ross",
    "mike dean",
    "chris paul",
    "zoya akhtar",
    "#waigurumustgo",
    "john lewis",
    "andre drummond",
    "matt forte",
    "star wars",
    "noel gallagher",
    "#worldseries",
    "#showtimebigaytodo",
    "fallout 4",
    "south sudan",
    "ashley young",
    "zack greinke",
    "$vrx",
    "#grantsnotdebt",
    "chris powell",
    "#theflash",
    "blake shelton",
    "dj drama",
    "jordin sparks",
    "japanese star wars",
    "jerry jones",
    "#southafricansvskenyans",
    "pc dave phillips",
    "sierra leone",
    "#kenyansvszimbabweans",
    "#indvsa",
    "gerald green",
    "#hearts",
    "bernie sanders",
    "#bjpgotopakistan",
    "melissa mathison",
    "#aldubwishmokayako",
    "#projectrunway",
    "shoaib malik",
    "robbie savage",
    "exo",
    "tony bennett",
    "#mma2015",
    "#aldenworthywithsnowcaps",
    "cam newton",
    "kendall jenner",
    "mcdavid",
    "#showtimehousemates",
    "martha ford",
    "#gbvsden",
    "#proudofonedirection",
    "#foggy",
    "drew brees"
  )
}
