FROM tensorflow/tensorflow
RUN pip3 install joblib
RUN pip3 install nltk
RUN pip3 install tqdm
RUN pip3 install pyprind
RUN python3.4 -m nltk.downloader --dir=/usr/local/share/nltk_data perluniprops punkt